### ISSUE TITLE
A few  things

### ISSUE THREAD

**Issue by b-t-k** [johnrambow/p-g-wodehouse_a-gentleman-of-leisure#1]
Great job on all those elisions! 

## Editorial commits
*Just a few notes:* 
Try to keep the various editorial commits separate. Alex doesn't insist we do all the extra modernization of hyphens etc. — we can just stick with the modernize word list and suggest words to be added — but if you choose to do them, it's better to do each as a separate commit so they can be reverted as necessary.

- The title case fix is not [editorial]
- semanticating the titles of books is not [editorial]
- Adding the dropped text *is* [editorial]

As far as I'm concerned all the above is fine as is (Alex may override me) but something to note for next time.

- “Police-captain” — having gone to all the trouble of modernizing those words I wonder why you chose to leave police-captain hyphenated?

## Overall
Some hints:
- Do searches for \<i to find unsemanticated italics.
- Do searches for [A-Z]\. to find caps followed by a period to find abbreviated names

### Chapter 1
- *Cyrus K. Higgs* needs abbr/name semantic (in several places)
- ill-fated \<i>Belle\</I> needs title semantic

### Chapter 3
- *of M. Blanc* and  needs abbr/name semantic
-  *Patrolman J. McEachern* needs abbr/name semantic

### Chapter 6
- need semantics on "A che la morte" — for both song and language

### Chapter 8
- *E.C.* (again in Chapter 14) needs abbr semantic

### Chapter 12
- *savoir-faire* — This is in MW so you could drop the \<i\>

### colophon
- \<b epub:type="z3998:personal-name">D A Alexander\</b> needs abbr/name semantic (see P. G. Wodehouse above). Alex usually adds in the missing periods in the name abbreviation

### Content.opf
- some of those sentences are doozies and probably won't stand. I have yet to submit a long description that didn't get edited by Alex and it's often overly complex sentence structure that gets targeted. But you can leave it if you want, but do check again after it's published to see how well you did :-) 
- Jeeves and Wooster is the common reference—I'd drop the “Bertie”
- Your Production notes are fine but probably unnecessary; the modernization is a given

**Comment by johnrambow** [comment]
Great, thanks –everything ought to have been addressed in new commits. 

I had a couple follow-up questions/notes:
### Classifying commits
•	If I need to add italics to book titles, is that still considered noneditorial? Or should it be broken up into two commits, adding italics (editorial) and then semantics (noneditorial)?
•	The dropped text, I thought, should be noneditorial because it appeared it was dropped by the Gutenberg transcribers, but please let me know if I misunderstood. (In this case, I realized yesterday that I dropped the text **myself**, when deleting page numbers. Oops. But I want to make sure what to do with any mistakes that might pop up in future transcriptions.)

### Other stuff

- I'll break up the [Editorial] commits much in the future, thx. 
- "Police captain" prob. does look better as two words, so I fixed that too. I had waffled, since it seemed a bit like an official title. 
- And thanks for all the info about semiotics. I’ll reread that section of the manual, because there are a lot. The searches will be useful.
- I cut the description down, though of course it can always be cut more.

**Comment by b-t-k** [comment]
Looks good. I will let Alex know.

"Editorial" in this case is generally anything we may change at some time in the future, is a judgement call, or is a major deviation from the published scans like updating spellings etc. I guess adding the missing text back in doesn't really count except if you transcribed it, it makes it easier for the reviewer to know they should check it. Italics and semantics are part of the normal process of "semanticating" so are don't especially need to be reviewed—editorial is a bit misleading..maybe if you think of it as limited to substantive edits rather than a mechanical edits you'll be closer...although not really.... Same with removing the page no., that's just part of general clean up of Gutenberg's coding, so not considered editorial at all. I generally do all that stuff before the first commit.

Good job — nice to see more "publishing" oriented people join in as we are often top heavy with literature-loving coders who make (to me) the oddest choices/mistakes :-)

**Comment by johnrambow** [comment]
Great, thanks that does help clarify the "editorial" question. 

I've been learning so much about the tech side as I go -- I knew some HTML before, but not anything much about CSS, other than the term . . . And git and github were even more mysterious.

**Comment by b-t-k** [comment]
I tried to write a guide for my non-techie friends. It's not much, and still a work in progress but it does have some of the things I have learned along the way:  [https://b-t-k.github.io/](https://b-t-k.github.io/)

**Comment by johnrambow** [comment]
Thanks -- I didn't realize you wrote that guide, which has been helpful,
esp with my first job.

It also makes me wish a bit that I was back to using a Mac  -- I miss
Preview, for one thing.
